# Generated by Django 5.1.6 on 2025-03-11 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrative",
            "0002_alter_block_name_alter_coordination_name_room_banca_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="banca",
            name="professores_banca",
            field=models.ManyToManyField(
                limit_choices_to={"role": "teacher"},
                related_name="bancas_professores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
