# Generated by Django 5.1.6 on 2025-03-13 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0004_banca_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamentosala",
            name="block",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="administrative.block",
            ),
        ),
        migrations.AddField(
            model_name="agendamentosala",
            name="coordination",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="administrative.coordination",
            ),
        ),
    ]
