# Generated by Django 5.1.6 on 2025-03-13 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0005_agendamentosala_block_agendamentosala_coordination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamentosala",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="administrative.block",
            ),
        ),
        migrations.AlterField(
            model_name="agendamentosala",
            name="coordination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="administrative.coordination",
            ),
        ),
    ]
