# Generated by Django 5.1.6 on 2025-03-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0006_alter_agendamentosala_block_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamentosala",
            name="block",
        ),
        migrations.RemoveField(
            model_name="agendamentosala",
            name="coordination",
        ),
    ]
