# Generated by Django 5.1.6 on 2025-03-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0007_remove_agendamentosala_block_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamentosala",
            name="bloco",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="administrative.block",
            ),
        ),
        migrations.AddField(
            model_name="agendamentosala",
            name="coordenacao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="administrative.coordination",
            ),
        ),
    ]
