# Generated by Django 5.1.6 on 2025-04-03 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0008_agendamentosala_bloco_agendamentosala_coordenacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="banca",
            name="presidente",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bancas_presidente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
