# Generated by Django 5.1.6 on 2025-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_usuario_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("teacher", "Teacher"),
                    ("secretary", "Secretary"),
                ],
                default="admin",
                max_length=50,
            ),
        ),
    ]
